steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/front_end:latest', '-f', 'front_end/Dockerfile', '.']
  id: 'Build the container image'
  waitFor: ["-"]
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/front_end:latest']
  id: 'Push the container image to Container Registry'
  waitFor: ["Build the container image"]
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'fe-financial-tweet-sentiment'
  - '--image'
  - 'gcr.io/$PROJECT_ID/front_end:latest'
  - '--region'
  - 'europe-west1'
  id: 'Deploy container image to Cloud Run'
  waitFor: ["Push the container image to Container Registry"]
options:
  logging: CLOUD_LOGGING_ONLY
